version: '3'
services:
  battlesnake.cr:
    build: .
    network_mode: host
    ports:
      - '127.0.0.1:3001:3003'
    command: /app/battlesnake -p 3003
  enemy-battlesnake.cr:
    build: .
    network_mode: host
    ports:
      - '127.0.0.1:3002:3002'
    command: /app/battlesnake -p 3002
