version: '3'
services:
  battlesnake.cr:
    build: .
    network_mode: host
    ports:
      - '127.0.0.1:3001:3001'
    command: crystal run /app/src/battlesnake.cr -- -p 3001
  enemy-battlesnake.cr:
    build: .
    network_mode: host
    ports:
      - '127.0.0.1:3002:3002'
    command: crystal run /app/src/battlesnake.cr -- -p 3002
